services:
  traefik:
    image: "traefik:3.0"
    restart: always
    container_name: 'traefik.${COMPOSE_DOMAIN}'
    command:
        # settings
      - "--log.level=TRACE"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.network=${COMPOSE_NETWORK}"
      - "--providers.docker.defaultRule=Host(`{{ .ContainerName }}`)"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web_secure.address=:443"
      - "--certificatesresolvers.resolver.acme.email=ethanabrace@gmai.com"
      - "--certificatesresolvers.resolver.acme.storage=acme.json"
      - "--certificatesresolvers.resolver.acme.httpchallenge.entrypoint=web"

    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
networks:
  traefik:
    external: true
    name: ${COMPOSE_NETWORK}
