services:
  traefik:
    image: "traefik:3.0"
    restart: always
    container_name: 'traefik.localhost'
    command:
        # settings
      - "--log.level=TRACE"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.network=traefik_default"
      - "--providers.docker.defaultRule=Host(`{{ .ContainerName }}`)"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$HOME/.config/braceyourself/compose/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"